#!/usr/bin/env python3

import time
import os
from sys import stderr
import argparse
import signal
import subprocess
import json
from random import shuffle


def msg(s):
    print(s, file=stderr, flush=True)


class VideoManager:
    """Play video files, keep track of history"""
    video = None
    start_time = None
    pos = 0
    errors = 0
    cmd = ('omxplayer', '--pos', '{}', '--no-osd')

    def __init__(self, wd):
        """Initialize self.

        :param wd: Working directory
        """
        self.wd = wd
        self.dump_file = os.path.join(wd, 'dump.json')
        self.history = []

    def write_dump(self):
        """Dump data to JSON file"""
        d = {'video': self.video,
             'pos': self.calculate_pos(),
             'history': self.history}
        with open(self.dump_file, 'w') as output_file:
            output_file.write(json.dumps(d))

    def read_dump(self):
        """Load data from JSON file"""
        if os.path.exists(self.dump_file):
            with open(self.dump_file, 'r') as input_file:
                d = json.loads(input_file.read())
            if 'history' in d and type(d['history']) is list:
                self.history = d['history']
            if 'video' in d and type(d['video']) is str:
                self.video = d['video']
            if 'pos' in d and type(d['pos']) is int:
                self.pos = d['pos']

    def set_random_video(self):
        """Get a random video from working directory"""
        if self.video:
            self.start_time = time.time()
            return True
        files = self.list_videos()
        shuffle(files)
        for vid in files:
            if vid in self.history:
                continue
            self.video = vid
            self.pos = 0
            return True
        return False

    def calculate_pos(self):
        """Calculate the playback position in the currently playing video"""
        if self.start_time:
            # Back up 30 sec
            p = int(time.time() - self.start_time + self.pos - 30)
            if p < 0:
                p = 0
            return p
        else:
            return 0

    def play_video(self):
        """Play a video"""
        self.write_dump()
        msg('playing: ' + self.video)
        cmd = [arg.replace('{}', str(self.pos)) for arg in self.cmd] + [os.path.join(self.wd, self.video)]
        self.start_time = time.time()
        subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        if self.calculate_pos() == 0:
            self.errors = self.errors + 1
        else:
            self.errors = 0
        if self.errors > 10:
            raise RuntimeError('video player restarting too quickly')
            
        self.add_to_history(self.video)
        self.video = None

    def add_to_history(self, video):
        """Add a video to the history and trim it to half of the amount of videos"""
        max_len = len(self.list_videos()) // 2
        self.history.append(video)
        self.history = self.history[-max_len:]

    def list_videos(self):
        """Return a list of all MP4 files in working dir"""
        v = [f for f in os.listdir(self.wd) if f.lower().endswith('.mp4') if os.path.isfile(os.path.join(self.wd, f))]
        return v


def handler(signal, frame):
    raise KeyboardInterrupt

signal.signal(signal.SIGTERM, handler)


parser = argparse.ArgumentParser(prog='jwb-rpi',
                                 usage='%(prog)s [DIR] [COMMAND]',
                                 description='Shuffle and play videos in DIR')
parser.add_argument('dir',
                    nargs='?',
                    metavar='DIR',
                    default='.')
parser.add_argument('cmd',
                    nargs=argparse.REMAINDER,
                    metavar='COMMAND',
                    help='video player command, "{}" gets replaced by starting position in secs')
args = parser.parse_args()

m = VideoManager(args.dir)
if len(args.cmd) > 0:
    m.cmd = args.cmd

# JSONDecodeError was added to Python 3.5
if hasattr(json, 'JSONDecodeError'):
    JSONDecodeError = json.JSONDecodeError
else:
    JSONDecodeError = ValueError

try:
    m.read_dump()
except JSONDecodeError:
    pass

showmsg = True
try:
    while True:
        if m.set_random_video():
            m.play_video()
            showmsg = True
        else:
            if showmsg:
                msg('no videos to play yet')
                showmsg = False
            time.sleep(10)
            continue
except KeyboardInterrupt:
    msg('aborted')
    m.write_dump()
