#!/usr/bin/env python3
import os
from sys import stderr

from jwlib import JWPubMedia, DefaultArgumentParser, JWOutputFactory
import jwlib.output as jo

parser = DefaultArgumentParser(prog='nwt-index',
                               usage='%(prog)s [options] [DIR]',
                               description='Index or download sound recordings from jw.org')
parser.add_default_arguments(['--quiet',
                              '--mode',
                              '--lang',
                              '--download',
                              'work_dir'])
# TODO
# parser.add_argument('--config')
parser.add_argument('--book',
                    metavar='NUM',
                    help='bible book to index')
parser.add_argument('--pub',
                    metavar='CODE',
                    help='publication to index')
parser.add_argument('--silver',
                    action='store_const',
                    const='nwt',
                    dest='pub',
                    help='index the 2013 revised NWT')

jw = JWPubMedia()
# Default values, not set by JWPubMedia
jw.work_dir = '.'
jw.mode = None
parser.parse_args(namespace=jw)
mode = jw.mode

data = jw.parse()

# Since the language check is done inside jw.parse() we do it before the rest of the checks
if not mode and not jw.download:
    print('please use --mode or --download', file=stderr)
    exit(1)

wd = jw.work_dir
subdir = jw.pub + '-' + jw.lang

if not mode or mode == 'stdout':
    subdir = ''

jw.download_all(os.path.join(wd, subdir))

if mode == 'filesystem':
    jo.clean_symlinks(os.path.join(wd, subdir), quiet=jw.quiet)

output = JWOutputFactory(data, include_keyname=True)
output.run(mode, wd, subdir)
