M_NONE = ''
M_FILESYSTEM = 'filesystem'
M_HTML = 'html'
M_HTML_TREE = 'html_tree'
M_M3U = 'm3u'
M_M3U_MULTI = 'm3u_multi'
M_M3U_TREE = 'm3u_tree'
M_RUN = 'run'
M_STDOUT = 'stdout'
M_TXT = 'txt'

MODES = M_FILESYSTEM, M_HTML, M_HTML_TREE, M_M3U, M_M3U_MULTI, M_M3U_TREE, M_RUN, M_STDOUT, M_TXT
MODES_WITH_MEDIA_SUBDIR = M_FILESYSTEM, M_HTML, M_HTML_TREE, M_M3U, M_M3U_MULTI, M_M3U_TREE
MODES_WITH_INDEX_SUBDIR = M_FILESYSTEM, M_HTML_TREE, M_M3U_TREE
MODES_WITH_SINGLE_FILE = M_HTML, M_M3U, M_TXT

SORT_NONE = ''
SORT_NEW = 'newest'
SORT_OLD = 'oldest'
SORT_NAME = 'name'
SORT_RANDOM = 'random'
SORTS = SORT_NEW, SORT_OLD, SORT_NAME, SORT_RANDOM

API_BASE = 'https://b.jw-cdn.org/apis/mediator/v1'

CATEGORY_DEFAULT = 'VideoOnDemand'
CATEGORY_LATEST = 'LatestVideos'
CATEGORY_SONGS = 'VODSJJMeetings'

TAG_HIDDEN = 'WWWExclude'
